# Generated by Django 4.2.4 on 2023-09-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_person_trade_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Trade',
        ),
    ]
